<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Array Grid Example</title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/grid-examples.css" />

    <!-- Common Styles for the examples -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/examples.css" />
    <!-- GC -->
    <!-- LIBS -->
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/adapter/ext/ext-base.js"></script>
    <!-- ENDLIBS -->

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ext-all.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/array-grid.js"></script>

</head>
<body>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js//examples.js"></script><!-- EXAMPLES -->
<h1>Array Grid Example</h1>
<p>This example shows how to create a grid from Array data.</p>
<p>Note that the js is not minified so it is readable. See <a href="<?php echo $this->baseUrl(); ?>/js/array-grid.js">array-grid.js</a>.</p>

<div id="grid-example"></div>
</body>
</html>
